### ISSUE TITLE
mosaic affecting dplyr summarise() 

### ISSUE THREAD

**Issue by rudeboybert** [ProjectMOSAIC/mosaic#625] opened 2016-11-05 16:35 UTC
Hello mosaic authors, loading the `mosaic` package is affecting `dplyr` functionality. I can't speak to anything more general than the MWE below: computing the mean of a logical vector. This returns `Error: variable names are limited to 10000 bytes` as an error.

```
x <- sample(c(TRUE,FALSE), size = 10000, replace = TRUE)
mean(x)
  
library(dplyr)
# Correct behavior
data_frame(test=x) %>% 
  summarize(mean(test))

library(mosaic)
# Error message
data_frame(test=x) %>% 
  summarize(mean(test))
```

**Comment by rudeboybert** [comment] 2016-11-05 16:44
Sorry, I forgot my `sessionInfo()`

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mosaic_0.14.4     Matrix_1.2-7.1    mosaicData_0.14.0 ggplot2_2.1.0    
[5] lattice_0.20-34   dplyr_0.5.0      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      tidyr_0.6.0      assertthat_0.1   MASS_7.3-45     
 [5] grid_3.3.1       R6_2.1.3         plyr_1.8.4       gtable_0.2.0    
 [9] DBI_0.5-1        magrittr_1.5     scales_0.4.0     lazyeval_0.2.0  
[13] ggdendro_0.1-20  splines_3.3.1    tools_3.3.1      munsell_0.4.3   
[17] colorspace_1.2-6 gridExtra_2.2.1  tibble_1.2    
```

**Comment by nicholasjhorton** [comment] 2016-11-05 17:03
Randy, 

Any thoughts?  Certainly this works with the following change:

x <- sample(c(TRUE,FALSE), size = 10000, replace = TRUE)
mean(x)

library(mosaic)
# Error message
data_frame(test=x) %>% 
  summarize(mean(test))

library(mosaic)
# This works
data_frame(test=x) %>% 
  summarize(base::mean(test))


> On Nov 5, 2016, at 12:35 PM, Albert Y. Kim <notifications@github.com> wrote:
> 
> Hello mosaic authors, loading the mosaic package is affecting dplyr functionality. I can't speak to anything more general than the MWE below: computing the mean of a logical vector. This returns Error: variable names are limited to 10000 bytes as an error.
> 
> x <- sample(c(TRUE,FALSE), size = 10000, replace = TRUE)
> mean(x)
>   
> library(dplyr)
> # Correct behavior
> data_frame(test=x) %>% 
>   summarize(mean(test))
> 
> library(mosaic)
> # Error message
> data_frame(test=x) %>% 
>   summarize(mean(test))
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by rudeboybert** [comment] 2016-11-05 17:06
I realized at the same time as Nick's message that this error is due to `mosaic` masking `base::mean()` with `mosaic::mean()`. Is there a better work around than having to explain to novice students that they now have to do `PACKAGENAME::FUNCTION()`, especially for a function as core as `mean()`?

**Comment by rpruim** [comment] 2016-11-07 14:04
This is a bug.  It comes from our attempts to play with `mean.Matrix()`.  I'm hopeful we can fix this, but I want to think about it a bit more carefully before committing.  (In may be that the offending code is simply cruft from the old days of supporting `mean(length, data = KidsFeet)`, in which case I can simply remove my hack for trying to figure out whether we have a matrix with forcing a promise when the object doesn't exist.

The only ways I have been able to trigger this bug so far is with large logical vectors (see below) and this suggests some work-arounds until I get this fixed:

```r
TF <- c(TRUE, FALSE)
data_frame(x = resample(TF, 100)) %>% summarise(mean(x))
## # A tibble: 1 × 1
##   `mean(x)`
##       <dbl>
## 1      0.52
data_frame(x = resample(TF, 100000)) %>% summarise(mean(x))
## Error in eval(substitute(expr), envir, enclos) : 
##   variable names are limited to 10000 bytes
data_frame(x = resample(0:1, 1000000)) %>% summarise(mean(x))
## # A tibble: 1 × 1
##   `mean(x)`
##       <dbl>
## 1  0.500311
data_frame(x = resample(TF, 100000)) %>% summarise(mean(~x, data = .))
## # A tibble: 1 × 1
##   `mean(~x, data = .)`
##                  <dbl>
## 1              0.49889
```

`lazyeval`'s documentation doesn't give me enough to figure out why long logicals are a problem, and the error is thrown inside `.Call(expr_find_, quote(x), environment())`, so we're pretty deep in the bowels of `lazyeval` when this happens.

**Comment by rpruim** [comment] 2016-11-07 14:07
My proposed fix solves this issue:

```r
data_frame(x = resample(TF, 100000)) %>% summarise(mean(~x, data = .))
## # A tibble: 1 × 1
##   `mean(~x, data = .)`
##                  <dbl>
## 1              0.50058
```

I just have to figure out if it will break anything else or is (as I hope) a vestige of a by-gone era.

**Comment by rpruim** [comment] 2017-05-20 12:01
I haven't noticed any other problems caused by this fix.  So closing.

**Closed by rpruim** 2017-05-20 12:01 UTC
