### ISSUE TITLE
Less Volume URL in mosaic-resources still references lattice functions

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#739] opened 2019-06-22 21:30 UTC
see "Less Volume" link in https://cran.r-project.org/web/packages/mosaic/vignettes/mosaic-resources.html

**Comment by rpruim** [comment] 2019-08-14 17:16
Interestingly, the Rmd file has already been updated to use ggformula, so I think the issue is with the rawgit URL.  

I'm going to try just moving this into vignettes in the normal way.  I don't recall anymore what issue we were trying to resolve by handling it in a different way years ago.

**Comment by rpruim** [comment] 2019-08-15 00:22
I've moved two things from ExtraDocs into vignettes and updated the resources vignette to reflect the change.

**Closed by rpruim** 2019-08-15 00:22 UTC
