### ISSUE TITLE
weirdness with xqchisq and df=1

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#581] opened 2016-04-05 13:15 UTC
xqchisq(.95, df=2)

works fine for me, but

xqchisq(.95, df=1)

generates a degenerate plot.  Am I doing something obviously wrong?

![image](https://cloud.githubusercontent.com/assets/530542/14282890/b4628fea-fb0e-11e5-9281-13c31fa271f0.png)

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tidyr_0.4.1       knitr_1.12.3      readr_0.2.2       xkcd_0.0.5       
 [5] extrafont_0.17    mdsr_0.1.1.9015   bigrquery_0.2.0   gmodels_2.16.2   
 [9] mosaic_0.13.0     mosaicData_0.13.0 car_2.1-2         ggplot2_2.1.0    
[13] lattice_0.20-33   dplyr_0.4.3      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4          gtools_3.5.0         assertthat_0.1       digest_0.6.9        
 [5] R6_2.1.2             plyr_1.8.3           acepack_1.3-3.3      MatrixModels_0.4-1  
 [9] httr_1.1.0           lazyeval_0.1.10.9000 curl_0.9.6           minqa_1.2.4         
[13] gdata_2.17.0         SparseM_1.7          extrafontdb_1.0      nloptr_1.0.4        
[17] rpart_4.1-10         Matrix_1.2-4         rmarkdown_0.9.5      devtools_1.10.0     
[21] splines_3.2.3        RMySQL_0.10.8        lme4_1.1-11          stringr_1.0.0       
[25] foreign_0.8-66       munsell_0.4.3        httpuv_1.3.3         mgcv_1.8-12         
[29] htmltools_0.3.5      nnet_7.3-12          openssl_0.9.2        gridExtra_2.2.1     
[33] Hmisc_3.17-2         withr_1.0.1          MASS_7.3-45          grid_3.2.3          
[37] nlme_3.1-126         jsonlite_0.9.19      Rttf2pt1_1.3.3       gtable_0.2.0        
[41] DBI_0.3.1            git2r_0.14.0         magrittr_1.5         scales_0.4.0        
[45] stringi_1.0-1        reshape2_1.4.1       latticeExtra_0.6-28  ggdendro_0.1-18     
[49] Formula_1.2-1        RColorBrewer_1.1-2   tools_3.2.3          parallel_3.2.3      
[53] pbkrtest_0.4-6       survival_2.38-3      yaml_2.1.13          colorspace_1.2-6    
[57] cluster_2.0.3        memoise_1.0.0        quantreg_5.21    
```

**Comment by nicholasjhorton** [comment] 2016-04-05 13:16
I think that there's a problem with the default xlim/ylim:

xqchisq(.95, df=1, xlim=c(0, 5), ylim=c(0, 2))

**Comment by rpruim** [comment] 2016-04-05 21:31
The plot is not degenerate; it is there and is "correct", you just don't like it the choice of y-scaling.  The problem is that 
$$
\lim_{x \to 0} dchisq(x, df=1) = \infty
$$

More to the point, we get
```
dchisq( qchisq(0.001, df= 1), df=1 )
## [1] 318.3096
```
so the y-scale goes up into the 300's be default.  I'm trying to think of something other than an ugly hack that would prevent this.  Perhaps we could only plot points for which y is less than some multiple of the IQR of the set of y values.  That would truncate away values that are much bigger than the rest.

**Comment by rpruim** [comment] 2016-04-05 21:46
I've changed the default `ylim` from

```r
  if (missing(ylim)) {
    ylim = c(0, 1.4 * max(ydata, na.rm = TRUE))
  }

```
to
```r
  if (missing(ylim)) {
    ylim = c(0, 1.6 * quantile(ydata, 0.95, na.rm = TRUE))
  }
```
The result for your example above is now this:

![image](https://cloud.githubusercontent.com/assets/722231/14298993/06c90646-fb56-11e5-978a-39864435f155.png)

One could discuss particular quantiles and multipliers, but something like this seems reasonable.

**Comment by nicholasjhorton** [comment] 2016-04-05 23:15
That looks *much* better, though it's still not displaying the values of 0.95 and 0.05.

Nick

> On Apr 5, 2016, at 5:46 PM, Randall Pruim <notifications@github.com> wrote:
> 
> I've changed the default ylim from
> 
>   if (missing(ylim
> )) {
>     
> ylim = c(0, 1.4 * max(ydata, na.rm = TRUE
> ))
>   }
> 
> to
> 
>   if (missing(ylim
> )) {
>     
> ylim = c(0, 1.6 * quantile(ydata, 0.95, na.rm = TRUE
> ))
>   }
> 
> The result for your example above is now this:
> 
> 
> 
> One could discuss particular quantiles and multipliers, but something like this seems reasonable.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment] 2016-04-05 23:22
I can fix that by doing things slightly differently and plotting the text also based on the truncated max rather than the actual max.  There will be some cases where the text bleeds into the plot, however.

Pick your poison:

![image](https://cloud.githubusercontent.com/assets/722231/14301189/bb14f92c-fb63-11e5-865f-c4ac500ae5b2.png)

**Comment by rpruim** [comment] 2016-06-05 23:29
I'm closing this.  Reopen if you find other cases that work poorly or have a suggestion for a different heuristic to use to set the default plot window.

**Closed by rpruim** 2016-06-05 23:29 UTC
